# We need 2 services here
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atk-demo.fullname" . }}-frontend
  labels:
    {{- include "atk-demo.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "atk-demo.selectorLabels" . | nindent 4 }}
