apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saasty-apps-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appSpace }}
