apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atk-demo
spec:
  destination:
    namespace: atk-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/atk-demo
    repoURL: 'https://github.com/atk4/infrastructure/'
    targetRevision: HEAD
    helm:
      releaseName: atk-demo
      valueFiles:
        - values.yaml






  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
