apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    namespace: atk-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/atk-demo
    repoURL: 'https://github.com/atk4/infrastructure/'
    targetRevision: HEAD
    helm:
      parameters:
        - name: replicaCount
          value: '3'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
