apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview.saasty.io
spec:
  destination:
    namespace: saasty-preview
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  source:
    path: helm/saasty
    repoURL: 'https://github.com/atk4/infrastructure/'
    targetRevision: HEAD
    helm:
      parameters:
        - name: replicaCount
          value: '1'

      values: |
        version: develop
        fullnameOverride: saasty-preview
        imagePullSecrets:
          - name: cfcr
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: admin_dsn

        env: []

        host: preview.saasty.io


        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
          hosts:
            - host: preview.saasty.io
              paths: ["/"]
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
