apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: stable/traefik
    repoURL: 'https://github.com/helm/charts/'
    targetRevision: HEAD
    helm:
      parameters:
        - name: acme.email
          value: me@nearly.guru
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false