apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: stable/traefik
    repoURL: 'https://github.com/helm/charts/'
    targetRevision: HEAD
    helm:
      values: |
        dashboard:
          enabled: true
          domain: traefik.saasty.io
        rbac:
          enabled: true
        ssl:
          enabled: true
          enforced: true
        acme:
          enabled: true
          email: me@nearly.guru
          logging: true
          challengeType: "dns-01"
          domains:
            enabled: true
            domainList:
              - saasty.io
              - www.saasty.io
              - traefik.saasty.io

          dnsProvider:
            name: digitalocean
            existingSecretName: acme-dnsprovider-config


#      parameters:
#        - name: acme.email
#          value: me@nearly.guru
#        - name: accessLogs.enabled
#          value: "true"
#
#        - name: dashboard.enabled
#          value: "true"
#        - name: dashboard.domain
#          value: traefik.agiletoolkit.org
#        - name: debug.enabled
#          value: true
#
#        - name: rbac.enabled
#          value: true
#
#        - name: acme.enabled
#          value: true
#        - name: acme.onHostRule
#          value: true
#        - name: acme.logging
#          value: true
#        - name: acme.acmelogging
#          value: true
#        - name: acme.email
#          value: me@nearly.guru
#        - name: acme.staging
#          value: true
#        - name: acme.challengeType
#          value: dns-01
#        - name: acme.dnsProvider.name
#          value: digitalocean




  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false