apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redirects
spec:
  destination:
    namespace: redirects
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  source:
    path: helm/redirects
    repoURL: 'https://github.com/atk4/infrastructure/'
    targetRevision: HEAD
    helm:
      parameters:
        - name: replicaCount
          value: '1'

      values: |
        version: develop
        fullnameOverride: redirects
        imagePullSecrets:
          - name: docker-cfg
        env: []

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
          hosts:
            - host: test.nearly.guru
              paths: ["/"]
            - host: dabasdraugi.lv
              paths: ["/"]
            - host: agiletoolkit.org
              paths: ["/"]
            - host: www.agiletoolkit.org
              paths: ["/"]
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
